apiVersion: v1
kind: ConfigMap
metadata:
  name: fleksitask-backend-config
  namespace: fleksitask
data:
  DEBUG: "false"
  MEDIA_DIR: "/app/media"
  MAX_UPLOAD_SIZE_MB: "5"
  ALLOWED_ORIGINS: '["https://fleksitask.com","https://admin.fleksitask.com"]'
  FRONTEND_URL: "https://fleksitask.com"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_TLS: "true"
  SMTP_FROM: "FleksiTask <enghoo2004@gmail.com>"
