apiVersion: v1
kind: Secret
metadata:
  name: fleksitask-secrets
  namespace: fleksitask
type: Opaque
stringData:
  SECRET_KEY: "change-this-in-production"
  DATABASE_URL: "postgresql+asyncpg://fleksi:password@postgres-service:5432/fleksitask"
  REDIS_URL: "redis://redis-service:6379/0"
  GOOGLE_CLIENT_ID: "956971520016-5bfps81m26gbufk85kn@pot51gbo1toq.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  SMTP_USER: "enghoo2004@gmail.com"
  SMTP_PASSWORD: "fgmplnfkouwbujrb"
