// This is a placeholder. The real file is auto-generated by `flutter pub get`.
// Do not edit manually.
#import <Flutter/Flutter.h>
#import "GeneratedPluginRegistrant.h"

@implementation GeneratedPluginRegistrant
+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
}
@end
